Adding a classifcationmap.xml file for the new documentation portal
ROCmSoftwarePlatform/AMDMIGraphX pull request #1049
Opened 2022-01-16 16:18 UTC by Rmalavally

Please approve

2022-01-17 14:32 UTC, causten commented
Pull request is to add an XML file to enable publishing the MIGraphX API content to an AMD portal

2022-01-17 16:50 UTC, pfultz2 approved these changes

2022-01-17 16:58 UTC, pfultz2 requested changes

2022-01-17 16:58 UTC, pfultz2 commented on doc/classification-maptest.xml
> +     x:Data="&amp;L&amp;&quot;Arial&quot;&amp;10&amp;K0000FF[AMD Official Use Only]&amp;1#"/>
We shouldn't have `[AMD Official Use Only]` in our public repos and source tarballs.

2022-03-03 21:19 UTC, causten commented
Changes will not be accepted.  Please open a new ticket along with a discussion once a working approach has been determined

2022-03-03 21:19 UTC, closed without merging