Add disable tests for one case that breaks in onnx v1.12.0
ROCmSoftwarePlatform/AMDMIGraphX pull request #1461
Opened 2022-11-18 00:33 UTC by TedThemistokleous

currently breaking for CI but we're not relying on CPU right now. Seems to be on the onnx side of this error.

2022-11-18 22:24 UTC, pfultz2 commented
But we dont use onnx 1.12 in CI?

2023-02-06 17:24 UTC, causten requested changes
Do not include the 22.04 work in to this PR.  It is good to include 3.10 and the 1.12.0 disable tests.   The CI runs of debug builds fail on 22.04 due to a compiler issue and that is taking longer then expected to get resolved.

2023-02-06 18:31 UTC, TedThemistokleous commented
@causten all good. Just reverted that change then

2023-02-06 18:32 UTC, causten approved these changes

2023-02-06 23:02 UTC, merged