Dynamic reference Softmax
ROCmSoftwarePlatform/AMDMIGraphX pull request #1475
Opened 2022-11-23 19:14 UTC by CharlieL7

* Simple change to make `Softmax` work with dynamic input shapes

2022-12-01 20:49 UTC, umangyadav approved these changes

2022-12-01 23:20 UTC, TedThemistokleous requested changes
Fix CI but otherwise looks fine

2022-12-06 22:22 UTC, bpickrel approved these changes
LGTM

2022-12-08 04:17 UTC, TedThemistokleous approved these changes
Looks in CI failing was the server stalling like we talked about @CharlieL7. Approved

2022-12-08 20:04 UTC, merged