Dynamic onnx gemm bias
ROCmSoftwarePlatform/AMDMIGraphX pull request #1527
Opened 2023-01-17 17:17 UTC by CharlieL7

* Adds support for parsing dynamic ONNX gemm bias input `C`
* Require this functionality for onnx model zoo's version of Resnet50

2023-01-19 00:06 UTC, umangyadav commented
> Not sure why it was checking for C.elements() < 0 or how it was working for the gemm_no_C test
 
 Where was this ? I see it is checking for  `element() > 0`. 

> Removed beta literal if it is 1 

This wasn't necessary. It would be cleaned up by simplify_algebra ( x * 1 = x) and dead-code-elimination.

2023-01-19 16:22 UTC, CharlieL7 commented
> > Not sure why it was checking for C.elements() < 0 or how it was working for the gemm_no_C test
> 
> Where was this ? I see it is checking for `element() > 0`.
> 
> > Removed beta literal if it is 1
> 
> This wasn't necessary. It would be cleaned up by simplify_algebra ( x * 1 = x) and dead-code-elimination.

* Typo, was C.elements > 0
* Agreed, alpha was not added this way so I changed beta to be consistent.

2023-01-19 22:00 UTC, umangyadav approved these changes

2023-01-19 22:03 UTC, umangyadav commented
> Agreed, alpha was not added this way so I changed beta to be consistent. 

We could have removed code related to `alpha ==1` check.  That would have simplified code instead of adding similar checks for `beta`. but Fine for now.

2023-01-19 22:11 UTC, umangyadav commented
> Not sure why it was checking for C.elements() > 0 or how it was working for the gemm_no_C test

It worked because of dead code elimination. Inside `onnx_test`, it is calling `optimize_onnx()`.

2023-01-19 22:13 UTC, umangyadav requested changes

2023-01-19 22:15 UTC, CharlieL7 commented on src/onnx/parse_gemm.cpp
> -            if(not float_equal(beta, 0.0f) and args[2]->get_shape().elements() > 0)
`shape.elements()` only checks lens. I think the check only catches if we default construct a shape or similar, but doesn't look like the onnx parser does that.

2023-01-20 16:16 UTC, TedThemistokleous commented on src/onnx/parse_gemm.cpp
> -            if(not float_equal(beta, 0.0f) and args[2]->get_shape().elements() > 0)
I agree with @CharlieL7 on this. How often are we going to see that case either? That isn't valid if we have zero length + strides. Do you mean if we have zero len/strides but say the shape is still dynamic?

2023-01-20 16:20 UTC, TedThemistokleous reviewed
Looks good just the one comment we should resolve about adding back the elements() > 0 check.

2023-01-20 16:48 UTC, umangyadav commented on src/onnx/parse_gemm.cpp
> -            if(not float_equal(beta, 0.0f) and args[2]->get_shape().elements() > 0)
I was thinking for scalar case. but `elements()` is not defined for dynamic shapes. So, I agree now that we shouldn't keep  `elements()>0` check. 

Saying that, how does the constructor makes a different ? We are taking shape of `migraphx::instruction` , and should be always be valid.

2023-01-20 17:08 UTC, TedThemistokleous commented on src/onnx/parse_gemm.cpp
> -            if(not float_equal(beta, 0.0f) and args[2]->get_shape().elements() > 0)
Some shape constructors will have the shape as empty with s{type, {}}  which comes up with empty items. That isn't valid onnx but its still possible with our shape constructor.

2023-01-20 17:13 UTC, umangyadav commented on src/onnx/parse_gemm.cpp
> -            if(not float_equal(beta, 0.0f) and args[2]->get_shape().elements() > 0)
But we are not taking shape of onnx's node. We are taking shape of migraphx::instruction.  Which can have empty lens. but even in  that case `elements()` is a valid call for static  shapes.

2023-01-20 17:17 UTC, TedThemistokleous commented on src/onnx/parse_gemm.cpp
> -            if(not float_equal(beta, 0.0f) and args[2]->get_shape().elements() > 0)
That's true. It would just resolve zero.

2023-01-20 17:18 UTC, TedThemistokleous approved these changes

2023-01-20 18:01 UTC, umangyadav approved these changes

2023-01-21 00:11 UTC, pfultz2 approved these changes

2023-01-21 04:31 UTC, merged