Select module op
ROCmSoftwarePlatform/AMDMIGraphX pull request #1569
Opened 2023-02-15 20:30 UTC by CharlieL7

2023-02-17 13:38 UTC, umangyadav commented
> Why was context.hpp changed to use std::move(queue)? This is the result of make generate
 If you rebase and do `make generate` it would go away now.

2023-02-22 22:03 UTC, TedThemistokleous commented on src/include/migraphx/op/select_module.hpp
> +        if(module_iter == submodule_list.end())
Add a test case to cover this

2023-02-22 22:35 UTC, TedThemistokleous commented on src/replace_allocate.cpp
> +        if(not main_offload_copy and not(m.use_local_alloc) and model.needs_out_params() and
Just take the compliment of the set of either outcome for allocs

not main_offload_copy and not(m.use_local_alloc) - > not(main_offload_copy or m.use_local_alloc)

2023-02-22 22:59 UTC, TedThemistokleous requested changes
Some comments /questions. 

Resolve the initial case as to why we;re seeing the zero alloc in your example earlier.

```
module: "main"
main:@0 = check_context::migraphx::version_1::gpu::context -> float_type, {}, {}
**main:@1 = hip::hip_allocate_memory[shape=float_type, {0}, {1},id=main:scratch] -> float_type, {0}, {1}**
data = @param:data -> dynamic, float_type, {[1, 4, 0], [2, 2, 0], [2, 2, 0]}
main:@3 = select_module[output_dyn_shapes=[dynamic, float_type, {[1, 4, 0], [2, 2, 0]}]](data), [batch_1, batch_2, batch_3, batch_4] -> [dynamic, float_type, {[1, 4, 0], [2, 2, 0]}]
main:@4 = get_tuple_elem[index=0](main:@3) -> dynamic, float_type, {[1, 4, 0], [2, 2, 0]}
main:@5 = @return(main:@4)

```

Seems benign, but I sense this is a placeholder for the other scratch pads for memory for each module.

2023-02-24 16:43 UTC, kahmed10 approved these changes

2023-02-25 05:27 UTC, TedThemistokleous approved these changes

2023-02-27 16:15 UTC, umangyadav approved these changes

2023-02-28 14:05 UTC, merged

2023-03-06 16:13 UTC, pfultz2 commented
> It is not clear to me why hip::sync_stream gets around the dangling reference issue.

`hip::sync_stream` is missing an `output_alias`, which is why it skips the checks.

> What I coded seems to work, but I do not understand when the copy to host occurs.

It might dangle when the user destroys the program and wants to still use the output buffer. Even if we shared the ownership to avoid the dangling reference, this would still require the scratch memory to stay alive just to use the output buffer, which we shouldnt be doing.

This should be using outputs parameters and allocations like we do for `if` and `loop` operators.