Add flag to trace onnx parser
ROCmSoftwarePlatform/AMDMIGraphX pull request #1687
Opened 2023-04-17 17:12 UTC by pfultz2

This will show the instructions that are inserted for each onnx operator. This should help debugging where certain instructions come from.

2023-04-17 18:57 UTC, TedThemistokleous approved these changes

2023-04-17 20:51 UTC, umangyadav approved these changes

2023-04-18 18:03 UTC, turneram approved these changes

2023-04-18 19:52 UTC, umangyadav requested changes
Tidy needs to be fixed.

2023-04-19 14:55 UTC, pfultz2 commented
Yea this is going to need a refactoring to the parse_graph functions.

2023-06-29 13:37 UTC, umangyadav approved these changes

2023-07-01 22:40 UTC, merged