Improvements to driver output
ROCmSoftwarePlatform/AMDMIGraphX pull request #1710
Opened 2023-04-24 15:05 UTC by pfultz2

- Use `generate_argument` instead of `generate_literal` for python output as `generate_literal` doesnt exists
- Shorten the names for variables from the main module
- Use prefix `p_` for parameters
- Use shorter variable `m` for main module in python

2023-05-15 16:10 UTC, TedThemistokleous requested changes
Looks good just fix the one unit test

2023-05-17 18:40 UTC, kahmed10 commented
Should be easy to fix (remove references to main module in test)

```
TEST_CASE(basic_graph_test)
{
    migraphx::program p = create_program();

    std::stringstream ss;
    p.print_graph(ss);
    std::string test = ss.str();
    std::cout << "test = " << test << std::endl;

    EXPECT(migraphx::contains(test, "digraph"));
    EXPECT(migraphx::contains(test, "rankdir=LR"));
    EXPECT(migraphx::contains(test, "\"@0\"[label=\"@literal\"]"));
    EXPECT(migraphx::contains(test, "\"y\"[label=\"@param:y\"]"));
    EXPECT(migraphx::contains(test, "\"x\"[label=\"@param:x\"]"));
    EXPECT(migraphx::contains(test, "\"@3\"[label=\"sum\"]"));
    EXPECT(migraphx::contains(test, "\"@4\"[label=\"sum\"]"));
    EXPECT(migraphx::contains(test, "\"x\" -> \"@3\""));
    EXPECT(migraphx::contains(test, "\"y\" -> \"@3\""));
    EXPECT(migraphx::contains(test, "\"@3\" -> \"@4\""));
    EXPECT(migraphx::contains(test, "\"@0\" -> \"@4\""));
    EXPECT(migraphx::contains(test, "[label=\"int64_type, {1}, {0}\"]"));
}
```

2023-05-24 14:08 UTC, pfultz2 commented
@TedThemistokleous Fixed the UT.

2023-05-24 14:58 UTC, TedThemistokleous approved these changes

2023-05-30 19:21 UTC, merged