Dynamic batch C++ API example
ROCmSoftwarePlatform/AMDMIGraphX pull request #1728
Opened 2023-05-01 17:06 UTC by CharlieL7

2023-05-04 15:49 UTC, TedThemistokleous approved these changes

2023-05-05 13:28 UTC, umangyadav requested changes

2023-05-05 13:28 UTC, umangyadav commented on examples/migraphx/cpp_dynamic_batch/README.md
> +The compiled dynamic batch model can be executed the same way as a static model by suppling the input data as `arguments` in a `program_parameters` object.
```suggestion
The compiled dynamic batch model can be executed the same way as a static model by supplying the input data as `arguments` in a `program_parameters` object.
```

2023-05-05 14:47 UTC, umangyadav approved these changes

2023-05-05 19:26 UTC, umangyadav commented
https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/1723/files#diff-c28f4a5d7fd1567f97c3460bdc5b3ff350740b6f65bcdfd8df89e8da795809e9 

This had cppcheck failure about redundant else stmt. It is causing problems for other PRs.

2023-05-08 16:48 UTC, merged