Ensure CI labels map correctly
ROCmSoftwarePlatform/AMDMIGraphX pull request #1780
Opened 2023-05-25 17:07 UTC by causten

The ONNX Runtime test suite was running on an unsupported GPU due to labeling logic.  This PR is to ally the ORT tests to run on any supported GPU and also ensures that nogpu doesn't run on GPU based servers

2023-05-25 17:24 UTC, JehandadKhan requested changes

2023-05-25 17:24 UTC, JehandadKhan commented on Jenkinsfile
> +        node_name = "${rocmtest_name} && (mi100 || mi200 || vega)";
```suggestion
        node_name = "${rocmtest_name} && (gfx908 || gfx90a || vega)";
```

2023-05-29 15:55 UTC, TedThemistokleous approved these changes

2023-05-29 17:52 UTC, umangyadav approved these changes

2023-05-29 18:40 UTC, merged