Enable tuning for MLIR
ROCmSoftwarePlatform/AMDMIGraphX pull request #1965
Opened 2023-07-15 00:37 UTC by pfultz2

2023-07-17 17:28 UTC, krzysz00 requested changes
I'm going to request this hold for #1961 , and, as a high level note, point out that failures (by way of `mlirLogicalResultFailed` in the high-level or backend pipelines, are proper errors. On the other hand, just because we gave you a tuning key doesn't mean it'll compile - you need to run the applicability pipeline to check.

2023-07-17 19:57 UTC, pfultz2 commented
> I'm going to request this hold for https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/1961 ,

That seems orthogonal to what I am doing here.

> On the other hand, just because we gave you a tuning key doesn't mean it'll compile - you need to run the applicability pipeline to check.

But if its not applicable it will fail compilation, so I dont see the problem.

2023-07-18 14:14 UTC, krzysz00 commented
The point is that if something fails compilation this is either because you've got a bad tuning parameter or because there's an actual bug ... or code that wouldn't work for any tuning parameter (usually in the case of the high-level pipeline).

It's possible that the applicability pipeline is an MIOpen-ism that isn't needed, but it still seems helpful to distinguish between "bad tuning parameter" and "something went wrong"

2023-07-27 12:58 UTC, umangyadav commented on src/targets/gpu/include/migraphx/gpu/mlir.hpp
> +tuning_config get_tuning_config_mlir(module m, const std::vector<shape>& inputs);
```suggestion
MIGRAPHX_GPU_EXPORT tuning_config get_tuning_config_mlir(module m, const std::vector<shape>& inputs);
```

2023-07-28 14:44 UTC, umangyadav approved these changes

2023-07-30 11:12 UTC, merged