Check that migraphx_gpu is not using device compilation in migraphx_gpu
ROCmSoftwarePlatform/AMDMIGraphX pull request #2050
Opened 2023-08-07 15:19 UTC by pfultz2

2023-08-07 15:23 UTC, umangyadav approved these changes

2023-08-11 19:15 UTC, TedThemistokleous requested changes

2023-08-11 19:15 UTC, TedThemistokleous commented on src/targets/gpu/no_device.cpp
> +
Add license file header here.

2023-08-22 20:56 UTC, TedThemistokleous commented on src/targets/gpu/no_device.cpp
> + * Copyright (c) 2015-2022 Advanced Micro Devices, Inc. All rights reserved.
make it 2023

2023-08-22 20:57 UTC, TedThemistokleous approved these changes

2023-08-30 00:17 UTC, merged