Improve error message when launching kernels fails
ROCmSoftwarePlatform/AMDMIGraphX pull request #2076
Opened 2023-08-15 16:01 UTC by pfultz2

This will let the user know which targets migraphx was built for and how to build migraphx for their gpu.

2023-08-15 19:01 UTC, umangyadav approved these changes

2023-08-15 20:11 UTC, TedThemistokleous requested changes
add licensing / fix tidy. Otherwise LGTM

2023-09-13 21:34 UTC, TedThemistokleous commented on src/targets/gpu/device/targets.hpp.in
> +* Copyright (c) 2015-2022 Advanced Micro Devices, Inc. All rights reserved.
2023

2023-09-13 21:34 UTC, TedThemistokleous commented on src/targets/gpu/device/targets.cpp
> + * Copyright (c) 2015-2022 Advanced Micro Devices, Inc. All rights reserved.
2023

2023-09-13 21:59 UTC, TedThemistokleous approved these changes
Just fix the dates but LGTM

2023-09-16 20:49 UTC, merged