Fuse skip layernorm
ROCmSoftwarePlatform/AMDMIGraphX pull request #683
Opened 2020-11-10 03:11 UTC by pfultz2

2020-11-19 20:10 UTC, pfultz2 commented
The code coverage changes is coming from serialize.hpp header, which I didnt change in this PR. @scxiao @kahmed10 Can you review this PR?

2020-11-20 16:24 UTC, kahmed10 approved these changes

2020-11-20 17:08 UTC, scxiao approved these changes

2020-11-20 17:47 UTC, kahmed10 requested changes
edit: nvm fp16 gelu hasn't been merged in yet.

2020-11-20 22:27 UTC, kahmed10 approved these changes

2020-11-20 22:31 UTC, merged